# Generated by Django 2.2.12 on 2020-07-06 14:49

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('alumnos', '0002_auto_20200706_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, verbose_name='_id')),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividad')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
            ],
            options={
                'db_table': 'matriclulas',
            },
        ),
    ]
