# Generated by Django 2.2.12 on 2020-10-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20200706_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='charlas_bebes',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='charlas_educa',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='cp',
            field=models.CharField(default=28850, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(default='Calle', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='dolencias_patologias',
            field=models.CharField(default='Destrozado', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='estudio_postural',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_inicio',
            field=models.DateTimeField(default='2020-07-06T16:53:00.000Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateTimeField(default='2020-07-06T16:53:00.000Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='forma_pago',
            field=models.CharField(default='Metálico', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='hipopresivos',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='localidad',
            field=models.CharField(default='Madrid', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='mail',
            field=models.EmailField(default='loa@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='mamas_bebes',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='mindfulness',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='movil',
            field=models.CharField(default='610101010', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='pago_matricula',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='pilates',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='pilates_infantil',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='provincia',
            field=models.CharField(default='Madrid', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='taller_meditacion',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(default='914751415', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='yoga',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='yoga_infanti',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
