# Generated by Django 2.2.12 on 2020-10-20 07:13

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, verbose_name='_id')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.Profesor')),
            ],
            options={
                'db_table': 'clases',
            },
        ),
    ]
